# Generated by Django 5.2.4 on 2025-07-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('sum', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Dummy Model',
                'verbose_name_plural': 'Dummy Models',
            },
        ),
    ]
